### ISSUE TITLE
Servers should never be forced to store passwords as cleartext

### ISSUE THREAD

**Issue by toolforger** [romis2012/aiohttp-basicauth#6]
The API as it is forces the server to keep the passwords in clear text.
(The risk scenario is the server being hacked and the password store getting copied, giving malicious actors too many abuse options for comfort.)

Fix suggestion:

- Instead of a password, accept `password_salt`, `password_cycles`, and `password_hash`.
- Use `hashlib.pbkdf2_hmac(incoming_password, password_salt, password_cycles)` and compare that with `password_hash`.
- Deprecate the `password` parameter, or (if possible) do a major release and remove it.

If you want to provide guidance to callers, you can recommend this:

```
import os
...
password_salt = os.urandom(16)
password_cycles = 1_000_000
```

**Comment by romis2012** [comment]
`aiohttp-basicauth` does not force you to store password in clear text. Just override check_credentials as described [here](https://github.com/romis2012/aiohttp-basicauth#advanced-usage)

**Comment by toolforger** [comment]
Ah right, I noticed that hint after I had written the comment. I meant to correct the issue but was distracted, sorry.
More importantly, you'll typically need to override anyway, because very few websites have just a single user, so very few if any projects will actually use this implementation.

Still. People will copy the idea. Particularly if they don't have the time to do it right, or lack the knowledge, or both (which is all too common).

Approaches that I see (one could find arguments for any of them):
- Make the constructor accept a `check_credentials` function. (Argument: Composition over inheritance; rarely an issue but if it _is_ an issue it can be a life saver for library users. Downside: Slightly more complicated to use, compatibility-breaking change.)
- Implement `check_credentials` as `pass`. (Argument: Throws an exception, forces library users to actually override it.)
- Implement `check_credentials` as `return False`. (Argument: Fails all logins, forces library users to override it as soon as the implement password-protected pages.)
- Implement `check_credentials` as `return True`. (Argument: Makes it easy to get a minimum implementation running quickly. Assumes that people will add actual login checking pretty soon anyway, which is likely true.)

I'm pretty impartial about which approach is taken, as long as it's not giving people insecure ideas ;-)

**Comment by romis2012** [comment]
We do not plan to change the API of `aiohttp-basicauth`. The existing interface seems to be optimal, on the one hand - simplicity, on the other - flexibility.

**Comment by toolforger** [comment]
Nah, an API that suggests unsafe practices is just inacceptable.
But no worries, I'll simply fork.
